### ISSUE TITLE
App quits unexpectedly on Mac

### ISSUE THREAD

**Issue by Allen-Dio** [diodechain/diode_drive_feedback#103]
Diode app will sometimes quit unexpectedly on mac and needs to be reopened.  Running Big Sir 11.3.1 Apple M1.  See attached doc for screenshot and crash report.
[Diode Drive quit unexpectedly.docx](https://github.com/diodechain/diode_drive_feedback/files/6789251/Diode.Drive.quit.unexpectedly.docx)

**Comment by dominicletz** [comment]
Thanks, @Allen-Dio for your report! Can you associate the crash to any specific action being performed? E.g. what happens before crashes?

**Comment by Allen-Dio** [comment]
Hi Dominic,

  This happens any time I want to do a Shut Down or Restart.  It doesn't
seem to be tied to a specific action other than that.  Eventually Mac OS
will ask if I want to force quit dDrive.  I just tried again and have
attached a screenshot of the message as well as my setup.  Thanks,

Allen

**Comment by dominicletz** [comment]
Thanks @Allen-Dio it's confirmed and we're looking into it!

**Comment by dominicletz** [comment]
We're rolling out a fix for this with the next update 1.2.7. Cheers and thanks for reporting!

**Comment by Allen-Dio** [comment]
Great news, looking forward to the update, thanks Dominic!
