### ISSUE TITLE
Update Banner Scrolls With Page

### ISSUE THREAD

**Issue by zach-pagel** [diodechain/diode_drive_feedback#109]
Software Details
--
![image](https://user-images.githubusercontent.com/17348062/129784964-7c14efa9-7b6d-41ba-a7c3-fcb261a1be5c.png)

Description
--
**Problem:** Update banner scrolls with page
<br>
**Steps to Reproduce:**
1. Delete ~/.config/ddrive/update-* folder
2. Start Diode Drive from binary, update banner should appear at the bottom
3. Find a page that has enough content to scroll
4. Scroll down the page
5. Observe banner floating up the page

<br>

**Screenshot:**
![update-bar-bug](https://user-images.githubusercontent.com/17348062/129786564-f14c26ad-1a45-40d6-84c9-54e5679ccc38.gif)

**Comment by hansr** [comment]
Fixed
