### ISSUE TITLE
Adding share from left hand menu always fails

### ISSUE THREAD

**Issue by jared-hess** [diodechain/diode_drive_feedback#112]
OS: Windows Windows 10 (build 18363), 64-bit edition
Launcher Build: 1.2.1
Base Version: 1.2.1
Patch Level: v1.2.5-3-g02e8b8e

On the left hand zone sidebar, trying to add a share by clicking the "+" icon next to "Shares" brings up a file selection window. But when selecting a file to share from this window and selectin "Open", an error dialog box appears with the text "The file/folder you have selected is outside the zone. Please select a file or folder to share from inside the zone." This always happens, even though the file selected was inside the zone. Using the share icon on the right hand side of the screen does work as expected.

**Comment by dominicletz** [comment]
Thanks @jared-hess . This is a windows specific bug and is fixed Patch Level 1.2.6 rolling out in the next couple of days
