### ISSUE TITLE
time string in chat has low contrast/ difficult to read

### ISSUE THREAD

**Issue by csrl** [diodechain/diode_drive_feedback#125]
The time string in chat for when a message was sent, on my screen is almost unreadable.  Between the very low contrast difference with the background (light gray on white) and the small font size, even my nose to the screen is hard to tell what the time stamp of the message is.  A font color with more contrast against white would be great.

**Comment by hansr** [comment]
Can you upload image?  This is how Mac shows up:

[image: image.png]

**Comment by csrl** [comment]
I'm referring to the time on the right hand side:
![image](https://user-images.githubusercontent.com/48568/149026915-57d5aac6-9346-4061-af6a-85370006edc6.png)

**Comment by hansr** [comment]
Fixed in 1.4.0+
