### ISSUE TITLE
Add simple messaging

### ISSUE THREAD

**Issue by hansr** [diodechain/diode_drive_feedback#4]
**Description:** It would be nice to be able to chat / message peers.

**Modification Area:** This would likely be a separate UI launched in the context of a peer of a drive.

**Why:** Since peers are already trustlessly connected, simple communication with them to coordinate file sharing or work-flow related discussions would be convenient.  It would be a benefit also to people who are looking for chat capabilities that don't use centralized servers.

**Comment by jimthedj65** [comment]
I think it would be desirable to have ui appear when clicking the peer for the message that way it would feel seamless.

**Comment by hansr** [comment]
Also valuable for sharing configuration / setting information with the remote peer.  Since nothing is stored centrally, could even be a more secure way to share confidential information, like keys - whereas it is less secure with other messaging mechanisms due to storage of data at rest.

**Comment by dominicletz** [comment]
Direct messaging is there now.
