### ISSUE TITLE
Rework notifications

### ISSUE THREAD

**Issue by hansr** [diodechain/diode_drive_feedback#41]
**Description:** All notifications currently pop up little dialog boxes.  It is not ideal, and they often get lost under other windows or forgotten.

**Modification Area:** All "actions" should use system notifications in concert with a main menu item, in concert with a notification/actions area in the web UI

**Why:** More seamless with OS behavior, not irritating, won't get forgotten

**Comment by dominicletz** [comment]
Invites now use os notifications
