### ISSUE TITLE
Merge Login/Signup Flow so choice is made in flow vs. parallel path

### ISSUE THREAD

**Issue by hansr** [diodechain/diode_drive_feedback#5]
All Systems, dDrive version 0.7.2

**Description:**
For a new user, especially someone who is already using Diode identities (e.g. Diode CLI), it is tempting to use the "Login" option for dDrive.  However, the UX flow for Login isn't clear how it is used, so it turns into a dead-end.  A UX that combines the Login/Signup flows with visual context could be helpful.

**Steps to reproduce:**
1) Install dDrive new (or kill the ~/.config/ddrive folder)
2) Observe the Login / Signup options both appear at same level on the menu

**Comment by hansr** [comment]
Also need to ensure the dDrive / CLI / Explorer BNS namespace is aligned so that a BNS name registered in any of the environments can be re-used in the other environments.

**Comment by dominicletz** [comment]
Done
