### ISSUE TITLE
Don't re-upload file upon move or name change

### ISSUE THREAD

**Issue by hansr** [diodechain/diode_drive_feedback#51]
**Description:** Don't re-upload content if the content is moved within the same drive or the name is changed.  Currently, if the content is moved or the name is changed, a "delete" is performed, and then the content is re-uploaded to the new name/location - the content is already resident on the peers, so it shouldn't need to be re-uploaded.

**Modification Area:** Transparent backend update.

**Why:** Makes name changes and re-organization quick with almost no-bandwidth impact.

**Comment by hansr** [comment]
This is a pretty significant UX problem.  Small name update (e.g. image name change from IMG2021asdfasdfasdf.jpg to dog_picture.jpg will force full re-upload).  I'll add bug label to this as it is unexpected - the issues with shares and linux file sync compound this problem.

**Comment by dominicletz** [comment]
This is fixed in v1.2.4
