### ISSUE TITLE
Browser session seems to continually load / reload

### ISSUE THREAD

**Issue by hansr** [diodechain/diode_drive_feedback#53]
**Environment:** MacOS 10.15.4, dDrive version 0.7.2p0.9.2, FireFox, Chrome

**Description:**
If I have a tab open for dDrive management web UI and open another, the new one seems to never stop loading.

**Steps to reproduce:**

1) Go to dDrive main menu -> manage - this will open a new tab with a unique session ID
2) Navigate somewhere in the dDrive web UI
3) Go to dDrive main menu -> manage - this will open another new tab with a new session ID
4) Observe the new session/tab continually is in the loading state

**Desired behavior:**
Step 4 should load as easily as step 1.  Ideally, the same tab will be re-used.

**Comment by dominicletz** [comment]
Fixed in beta v1.0
