### ISSUE TITLE
Diode Drive main app window spawns above my screen top

### ISSUE THREAD

**Issue by hansr** [diodechain/diode_drive_feedback#59]
**Environment:** MacOS 10.15.4, Windows 10 - Diode Drive version 0.1-4

**Description:**
When Diode Drive app window starts, it will sometimes load with the top of the window above my screen top, making it impossible to close the window without quitting the app.

**Steps to reproduce:**

1) Connect a large screen to a laptop with a smaller screen
2) Open Diode Drive app
3) Move app to top of screen
4) Close app window
5) Detach large screen
6) Open Diode Drive app
7) Observe top of app above screen height

**Desired behavior:**
Steps 2) and 7) should always spawn window top below top of screen

**Comment by dominicletz** [comment]
Windows has been resized and repositioned.
