### ISSUE TITLE
After accepting invite, zone list is not updated

### ISSUE THREAD

**Issue by hansr** [diodechain/diode_drive_feedback#62]
**Environment:** Diode Drive version 1.0.1-7, Windows 10

**Description:**
After accepting an invite, the list in the main Diode Drive app does not automatically update.  I have to close the app and relaunch it to see the new zone.

**Intended Behavior**
Upon accepting an invite, the new zone should be immediately listed in my left hand zone list.

**Comment by dominicletz** [comment]
Fixed in 1.0.2-1
