### ISSUE TITLE
Minor font color issue when verifying BNS name

### ISSUE THREAD

**Issue by zach-pagel** [diodechain/diode_drive_feedback#66]
**Operating system and version:** Ubuntu 20.04.2 LTS

**Diode Drive version:** 1.0.1

**Problem description:** Hard to read green text while checking BNS name

**Steps to reproduce:**
1. Create a new drive
2. Select invite
3. Input valid .diode address to peer with
4. Observe hard to read light green color

**Screenshot:**
![badgreen](https://user-images.githubusercontent.com/17348062/112742847-b49c4900-8f57-11eb-8c60-dbbe22b234ca.png)

**Comment by dominicletz** [comment]
Yeah, right on! We're replacing this with a new view @fayddelight is working on that

**Comment by hansr** [comment]
Same on MacOS 10.15.4
