### ISSUE TITLE
Notification shows wrong Zone

### ISSUE THREAD

**Issue by hansr** [diodechain/diode_drive_feedback#79]
**Environment:** MacOS 10.15.4, Diode Drive 1.2.0

**Description:**
When files are sync'd to my local from another peer, the notification shows the wrong zone.  For example, this file is not in the A...tal Zone shown, but it is the actual file that was updated.
![image](https://user-images.githubusercontent.com/275153/117541546-f59f7700-b046-11eb-8456-9720324a6deb.png)

**Steps to reproduce:**
Unsure.  I've observed this and have one other user report on this. 

**Desired behavior:**
Notification should show the correct Zone name.

**Comment by dominicletz** [comment]
Fixed in 1.2.1+4
