### ISSUE TITLE
Hide Password Field on Share

### ISSUE THREAD

**Issue by zach-pagel** [diodechain/diode_drive_feedback#81]
**OS:** MacOS Version 10.16
**Diode Drive Launcher Build:** 1.2.0
**Diode Drive Base Version:** 1.2.1
**Diode Drive Patch Level:** v1.2.1-1-1gb7d8ebc 

**Problem Description:** The password field when adding a share is a standard text box; therefore, MacOS tries to auto-correct the input into that field. It would be nice to have the field as a password field (hidden text) with an option to temporarily view the contents. 

**Steps to Reproduce:** Go to the share screen of any file or zone, then start typing something into the password field.

**Comment by dominicletz** [comment]
Done, thanks @zach-pagel
