### ISSUE TITLE
"Transaction Failed" if new account name includes capital letter

### ISSUE THREAD

**Issue by zach-pagel** [diodechain/diode_drive_feedback#85]
Software Details
--
**OS:** Linux Linux 5.8.0-53-generic x86_64
**Distro:** Ubuntu 20.04 LTS
**Diode Drive Launcher Build:** 1.2.0
**Diode Drive Base Version:** 1.2.1
**Diode Drive Patch Level:** v1.2.1-1-gb7d8ebc

Description
--
**Problem:** If a new account name contains a capital letter, Diode Drive responds with "Transaction Failed."

**Steps to Reproduce**
1. Start Diode Drive with an empty *~/.config/ddrive* directory
2. Try to sign up with a username that contains a capital letter

**Screencapture:** https://user-images.githubusercontent.com/17348062/118902026-631a9580-b8da-11eb-8bcf-1f528cf81af4.mp4

**Comment by dominicletz** [comment]
@fayddelight please have a look into this and fix if possible :-)

**Comment by fayddelight** [comment]
Fixed.
