### ISSUE TITLE
Invite Control Buttons Don't Function

### ISSUE THREAD

**Issue by zach-pagel** [diodechain/diode_drive_feedback#86]
Software Details
--
**OS:** Linux Linux 5.8.0-53-generic x86_64
**Distro:** Ubuntu 20.04 LTS
**Diode Drive Launcher Build:** 1.2.0
**Diode Drive Base Version:** 1.2.1
**Diode Drive Patch Level:** v1.2.2

Description
--
**Problem:** Reject, Accept, and Trash Bin buttons (circled in red) don't seem to perform any actions on the invites.

**Steps to Reproduce:** Go to profile->invites and try to interact with invites using the buttons.

**Screenshot**
![image](https://user-images.githubusercontent.com/17348062/119409185-86fc2380-bcac-11eb-8924-7de4bf322da3.png)

**Comment by hansr** [comment]
@zach-pagel  FYI - this has been fixed and will get pushed out next release - thanks for logging...
