### ISSUE TITLE
Invites are never received unless other Team Members are online

### ISSUE THREAD

**Issue by hansr** [diodechain/diode_drive_feedback#90]
**Software Details:** All @v.1.2.0+

**Problem:** If a new Team Member is invited to a Zone, they will not receive the invite, ever, unless at least one other already-active Team Member is online.  This is especially problematic for the very first Team Member invited to a new Zone, exacerbated if the users are, for example, located in Asia and North America, respectively.

**Desired Behavior:** An "invitee" should receive an invite even if the inviter is not online.

**Comment by dominicletz** [comment]
Fixed in v1.2.4
