### ISSUE TITLE
Hyperlinks in chat should be clickable

### ISSUE THREAD

**Issue by hansr** [diodechain/diode_drive_feedback#95]
**Software Details:** All platforms, @v.1.2.3-7+

**Problem:** If I send a URL to someone in a chat message, it is not clickable - they have to copy/paste in order to navigate to the URL

**Desired Behavior:** Auto-detect any full-formed URL and launch the default browser window upon click

**Comment by dominicletz** [comment]
@fayddelight please have a look at this

**Comment by fayddelight** [comment]
Works now.
