### ISSUE TITLE
File link / share page takes a long time to render

### ISSUE THREAD

**Issue by hansr** [diodechain/diode_drive_feedback#96]
**Environment:** Tested on MacOS 10.15.4, Diode Drive 1.2.4+ 

**Description:**
If I create a share link to a file and then provide it to someone else, when they open the link, the page can sometimes take 10+ seconds after it is rendered to complete loading so that the buttons are clickable.  Can this be optimized?

**Comment by hansr** [comment]
On the "first" drive, a new share created by an Asia team member will never actually render at all - unsure of cause.  Perhaps it is being served by a slow EU team member and this causes troubles??

**Comment by dominicletz** [comment]
Fixed mostly in v1.2.6
